config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :reviews, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '本格'},
    { id: 3, name: '叙述'},
    { id: 4, name: '警察'},
    { id: 5, name: 'イヤミス'},
    { id: 6, name: '医療'},
    { id: 7, name: 'SF'},
    { id: 8, name: '特殊'},
    { id: 9, name: '恋愛'},
    { id: 10, name: 'アクション'},
    { id: 11, name: '日常'},
    { id: 12, name: '短編'},
  ]
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :genre
  has_one_attached :image
  has_many :comments


  validates :title, :author, :genre, :content, presence: true
  
  validates :genre_id, numericality: { other_than: 1 }
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/reviews/#{comment.review.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:sentence).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @reviews = Review.all
  end

  def new 
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to root_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :author, :genre_id, :content, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysterynovel28446</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <script src ="index.js"></script> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="heading">
        <h1 class="title"><a href="/">ミステリーレビュー</h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
          <li class="nav-user">
            <% if user_signed_in? %>          
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              <%= link_to "投稿する", new_review_path, class: "post"%>
            <% else %>
              <%= link_to "ログイン", new_user_session_path, class: "post" %>
              <%= link_to "新規登録", new_user_registration_path, class: "post" %>
            <% end %>
          </li>
          <li class="background-red" id="genres">ジャンル</li>
        </ul>
        <ul class="show-lists hidden" id="pull-down">
          <li class="pull-down-list">本格</li>
          <li class="pull-down-list">叙述</li>
          <li class="pull-down-list">警察</li>
          <li class="pull-down-list">イヤミス</li>
          <li class="pull-down-list">医療</li>
          <li class="pull-down-list">SF</li>
          <li class="pull-down-list">特殊</li>
          <li class="pull-down-list">恋愛</li>
          <li class="pull-down-list">アクション</li>
          <li class="pull-down-list">日常</li>
          <li class="pull-down-list">短編</li>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer>
     <p>
       Copyright ミステリーレビュー 2020.
      </p>
    </footer>
  </body>
</html>

app/views/reviews/index.html.erb
<div class="contents">
  <% @reviews.each do |review| %>
    <div class ="content_title" >
      <%= image_tag review.image.variant(resize:'200x200'), class: 'review-image' if review.image.attached? %>
      <div class=title_author>
        <span>題名：<%= review.title %></span>
        <span class="author">著者名：
          <%= review.author%>
        </span>
      </div>
      <div class="content">
        <%= link_to review.content, review_path(review.id), method: :get %>
      </div>
    </div>
  <% end %>
</div>
      

app/views/reviews/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @review, local: true) do |form| %>
      <h3>レビューを書く</h3>
       <span class="image-file">画像</span>
       <%= form.file_field :image, class: 'image-hidden' %>
       <%= form.text_field :title, placeholder: "本の題名を入力してください", class: "form-title" %>
       <%= form.text_field :author, placeholder: "本の著者名を入力してください", class: "form-title" %>
       <%= form.collection_select(:genre_id, Genre.all, :id, :name, {}, class: "form-genre") %>
       <%= form.text_area :content, placeholder: "本のレビューを書いてください", rows: "20", class: "form-content" %>
       <%= form.submit "送信", class: "form-button" %>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="show-contents">
  <div class="image">
    <%= image_tag @review.image.variant(resize:'400x400'), class: 'review-image' if @review.image.attached? %>
  </div>
  <div class="show-content">
    <ul class="show-title">
      <li class="show-list">題名: <%= @review.title%></li>
      <li class="show-list">著者名: <%= @review.author%></li>
      <li class="show-list"><%= @review.content%></li>
    </ul>
    <ul class="edits">
    <% if user_signed_in? && current_user.id == @review.user_id %>
      <li class="edit">編集</li>
      <li class="edit">
        <%= link_to '削除', review_path(@review.id), method: :delete %>
      </li>
    <% end %>
    </ul>
    <div class="fav">いいね</div>
  </div>
</div>
<div class="forms">
  <div class="form">
    <% if current_user %>
      <%= form_with(model: [@review, @comment], local: true) do |form| %>
        <%= form.text_area :sentence, placeholder: "コメントを入力してください", rows: "2", class: "comment-title"%>
        <%= form.submit "送信", class: "comment-button" %>
      <% end %>
    <% else %>
      <strong><p>*** コメントの投稿には新規登録/ログインが必要です ***</p></strong>
    <% end %>
  </div>
  <div class="comments">
    <h3>＜コメント一覧＞</h3>
    <% if @comments %>
      <% @comments.each do |comment| %>
        <p>
          <strong><%=  comment.user.nickname %>:</strong>
          <%= comment.sentence %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>